### ISSUE TITLE
gst launcher and some features 

### ISSUE THREAD

**Issue by Kamukage3e** [selkies-project/selkies#89]
Yesterday I checked another git repo that shown a lot of configuration pipelines   https://gist.github.com/hum4n0id/2760d987a5a4b68c24256edd9db6b42b#display-test-video,  Can we use gst-launcher to create pipeline and run selkies -gstreamer ?.   Is it possible add feature session recording and JWT auth with secret key?

**Comment by ehfd** [comment]
The pipeline is embedded within gstwebrtc_app.py.

On top of the GStreamer pipeline, the Python code includes a signaling server and code to convey the input from the client web browser to the host X11 server.

**Comment by Kamukage3e** [comment]
I want to specify all configuration on server side like (fps, enable sound etc..) via JWT params and hide menu on the web client.  The Reason is  I have warning 
0:03:10.309652372   727 0x7f30381631e0 WARN              rtpsession gstrtpsession.c:2435:gst_rtp_session_chain_send_rtp_common:<rtpsession1> Can't determine running time for this packet without knowing configured latency.

**Comment by ehfd** [comment]
I am aware of the issue. The warning can be fixed by adding a bus handler. The rest can be done by you using GST-Python.

Because of the warning message rtpsession gstrtpsession.c:2435:gst_rtp_session_chain_send_rtp_common:<rtpsession0> Can't determine running time for this packet without knowing configured latency, add a message handler after it does Gst.Pipeline.new(). Something that's going to regularly pop messages from the bus and process them, or a GLib mainloop and a bus signal handler like in that [helloworld example](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-python/examples/helloworld.py).

This is required. But I don't have the time to immediately fix this. I left it out because it isn't a critical blocker.

The latency update should be called with `Gst.Bin.recalculate_latency()` in `bus_call` when `t == Gst.MessageType.LATENCY` in the [helloworld example](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-python/examples/helloworld.py).

@danisla Could you assist into this?

Or you could contribute. @Kamukage3e

**Comment by ehfd** [comment]
> Can we use gst-launcher to create pipeline and run selkies -gstreamer ?. Is it possible add feature session recording and JWT auth with secret key?

About this, I really don't know how it will work. Safest choice would be starting from the Python code - it's mostly the same as the command line pipeline connected with `|`.

**Comment by ehfd** [comment]
More questions from users:

is there any community guides how to install this project into self-hosted k8s?

I looked at .yml files, and as i can see, it's all configured for gcloud infrastructure, will it work on simple k8s? I'm talking about a full project, not just single gpu containers

as i can see, in project page it also have a gstreamer repo, operator etc. How to work with this? like load balancing and etc. (i want try to install vdi repo)

---

anyone have any experience trying to run selkies in systemd-nspawn containers rather than docker? I guess this applies to docker as well— I am not quite sure why it would be different..

I am struggling a bit with how to pass virtual devices created by uinput from the host to the container(s). evdev/libinput seems to find them, but xorg/wayland doesnt. they seem to get assigned to the host seat rather than container

**Comment by Kamukage3e** [comment]
@ehfd From where will I get get_bus()  ?   on start_pipeline like 
                mloop = GLib.MainLoop()
        self.bus = self.start_pipeline.get_bus()
        self.bus.add_signal_watch()
        self.bus.connect("message", bus_call, mloop)

**Comment by ehfd** [comment]
I am going to ask @danisla for this soon.

**Comment by Kamukage3e** [comment]
@ehfd If you explain me I will fix it

**Comment by ehfd** [comment]
```
    def start_pipeline(self):
        """Starts the GStreamer pipeline
        """

        logger.info("starting pipeline")

        self.pipeline = Gst.Pipeline.new()

        # Construct the webrtcbin pipeline with video and audio.
        self.build_webrtcbin_pipeline()
        self.build_video_pipeline()

        if self.audio:
            self.build_audio_pipeline()

        # Advance the state of the pipeline to PLAYING.
        res = self.pipeline.set_state(Gst.State.PLAYING)
        if res != Gst.StateChangeReturn.SUCCESS:
            raise GSTWebRTCAppError(
                "Failed to transition pipeline to PLAYING: %s" % res)
```

I'm not 100% sure, but apparently it should be done before `res = self.pipeline.set_state(Gst.State.PLAYING)`, and I am betting on `self.pipeline.get_bus()`. If not correct, `self.webrtcbin.get_bus()`

**Comment by Kamukage3e** [comment]
I tried to add bus_call via  pipeline and webrtcbin  but after starting pipeline Xfvb showing that " already running, quit"

**Comment by ehfd** [comment]
@danisla Priority Number 1 IMO
